use toeiconline;

ALTER TABLE userEntity MODIFY COLUMN name VARCHAR(255) NOT NULL;
ALTER TABLE userEntity MODIFY COLUMN password VARCHAR(255) NOT NULL;
ALTER TABLE userEntity MODIFY COLUMN roleid BIGINT(20) NOT NULL;

